version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    image: mothmon14682/pms:latest
    environment:
      - db_host=10.140.0.5:3306
      - db_name=${db_name}
      - db_username=${db_username}
      - db_password=${db_password}
    ports:
      - "8080:8080"