version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    image: mothmon14682/pms:latest
    environment:
      pms_db_host: ${pms_db_host}
      pms_db_name: ${pms_db_name}
      pms_db_username: ${pms_db_username}
      pms_db_password: ${pms_db_password}
