version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    image: mothmon14682/pms:latest
    environment:
      - db_host=db
      - db_name=${db_name}
      - db_username=${db_username}
      - db_password=${db_password}
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    image: mothmon14682/pms-db:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${db_password}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: 
