FROM maven:3.9-eclipse-temurin-21

RUN apt-get update && apt-get install -y wget gettext && \
    wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz && \
    tar -xzf apache-tomcat-9.0.85.tar.gz && \
    mv apache-tomcat-9.0.85 /opt/tomcat

WORKDIR /app
COPY . .

RUN mvn package -DskipTests

RUN rm -rf /opt/tomcat/webapps/*

RUN mkdir -p /opt/tomcat/webapps/ROOT && \
    cd /opt/tomcat/webapps/ROOT && \
    jar -xvf /app/target/pms.war

EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
