FROM maven:3.9-eclipse-temurin-21

RUN apt-get update && apt-get install -y wget gettext && \
    wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz && \
    tar -xzf apache-tomcat-9.0.85.tar.gz && \
    mv apache-tomcat-9.0.85 /opt/tomcat

WORKDIR /app
COPY . .

ARG db_host
ARG db_name
ARG db_username
ARG db_password

ENV db_host=$db_host
ENV db_name=$db_name
ENV db_username=$db_username
ENV db_password=$db_password

RUN mvn clean package

RUN rm -rf /opt/tomcat/webapps/*

RUN mkdir -p /opt/tomcat/webapps/pms && \
    cd /opt/tomcat/webapps/pms && \
    jar -xvf /app/target/pms.war

RUN cp /app/target/pms.war /opt/tomcat/webapps/


RUN envsubst < /app/src/main/resources/db.properties.example \
    > /opt/tomcat/webapps/pms/WEB-INF/classes/db.properties

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]
