- name: Deploy Docker container
  hosts: app_servers
  become: true

  vars:
    image_name: mothmon14682/pms:latest
    container_name: pms
    host_port: 8080
    container_port: 8080

  tasks:
    - name: Recreate container only if image changed
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        recreate: true
        restart_policy: always
        ports:
          - "{{ host_port }}:{{ container_port }}"
