pipeline {
    agent any

    environment {
        DB_CREDS = credentials('database-id')
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-id')
        pms_db_name = 'pms'
        pms_db_username = "${DB_CREDS_USR}"
        pms_db_password = "${DB_CREDS_PSW}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            agent {
                docker {
                    image 'maven:3.9-eclipse-temurin-21'
                    reuseNode true
                    args '-v $HOME/.m2:/root/.m2'
                }
            }

            steps {
                withEnv([
                    "pms_db_host=10.140.0.5",
                    "pms_db_name=${pms_db_name}",
                    "pms_db_username=${pms_db_username}",
                    "pms_db_password=${pms_db_password}"
                ]) {
                    sh '''
                        mvn -B -ntp clean test
                        mvn -B -ntp package -DskipTests
                    '''
                }
            }
        }

        stage('Docker build and push') {
            steps {
                sh 'docker build -t mothmon14682/pms:latest .'

                sh '''
                echo $DOCKERHUB_CREDENTIALS_PSW | docker login \
                  -u $DOCKERHUB_CREDENTIALS_USR \
                  --password-stdin
                '''

                sh 'docker push mothmon14682/pms:latest'
            }
        }

        stage('Deploy via Ansible') {
            steps {
                sh 'ansible-playbook -i jenkins/app_inventory.ini jenkins/deploy.yml'
            }
        }
    }

    post {
        always {
            // cleanup workspace
            cleanWs()
        }
    }
}
